### ISSUE TITLE
approot is set incorrectly with nonstandard ports

### ISSUE THREAD

**Issue by andrewthad** [snoyberg/keter#120]
In my `keter-config.yml` file, I have this:

    root: ..
    listeners:
      - host: "*4" # Listen on all IPv4 hosts
        port: 8000 # Could be used to modify port

In my `config/keter.yml` file, I have this:

    stanzas:                                                                                              
      - type: webapp                                                                                      
        exec: ../unthreat  # I moved this to a nonstandard location
        hosts:                                                                                            
          - unthreat.layer3com.com
    plugins:
      postgres: true

So, I'm using port 8000 instead of the usual port 80. However, the environment variable `APPROOT` still gets set to `http://unthreat.layer3com.com`. So, when I initially browse to the page at `http://unthreat.layer3com.com:8000`, it comes up, but all the links are broken. I would be happy to fix this if someone could show me where the relevant code is.

**Comment by snoyberg** [comment]
You need to set external-http-port or external-https-port, if memory serves. See: https://github.com/snoyberg/keter/blob/master/Keter/Types/V10.hs#L159. The issue is that there can be multiple listeners on different ports, and on top of that the listeners themselves may not know the truly external port (if there's a load balancer between the end user and keter). Therefore, you need to explicitly tell keter which port to use for generating URLs.

I can remember off-hand how keter deals with http vs https for this though.

**Comment by andrewthad** [comment]
Your right: https://github.com/snoyberg/keter/blob/master/etc/keter-config.yaml#L28
The explanation you gave makes it all make a lot more sense. Thanks.
