### ISSUE TITLE
Why keter?

### ISSUE THREAD

**Issue by 3noch** [snoyberg/keter#140]
I'm not a dev-ops pro but it seems like Keter's feature set overlaps significantly with nginx and Apache. Why would one choose Keter?

**Comment by angerman** [comment]
@3noch while it is true that keter *does* replicate some of the functionally that apache and nginx provide, this is mostly–to my understanding–a necessity to allow to elevate the need for nginx or apache altogether, in cases where such a setup is not needed. Yet you can perfectly fine run keter behind any other reverse proxy. If you want to have some other application say, serve static data (e.g. nginx).

What keter *does* offer, that is not covered by nginx or apache (or any other generic web server for that purpose), is the deployment of keter packages (See also https://github.com/creichert/keter-pkg). This includes a more intelligent restart mechanism that ensures that the new package does in fact actually start, before switch over; and the relevant log mechanics, so that logs for each app are nicely separated.

If you simply files to be dropped into the `incoming` folder, keter will take care of lauchning/restarting the apps. From an application developer perspective, this usually means that all you need to do to deploy the application is to `scp`, `sftp`, ... the keter package onto the server, and have keter take care of the rest (unpacking, launching, routing to the new app, etc.).

**Comment by 3noch** [comment]
@angerman Thank you! That's very helpful. Do you think that, for someone who is familiar with nginx/Apache, the current README is clear enough? I'm guessing if my familiarity with other technologies were better I would not have had this confusion.

Still, it might be better to play it safe and add a brief version of what you said to the README.

**Comment by angerman** [comment]
@3noch it's always debatable if documentation is good enough, and I'd usually say it's not, as it's really hard to get documentation right; you want to aim for concise, yet detailed enough documentation. @creichert what do you think about adding the blurb from above into a general introduction section in the REAMDE?

For the `nginx` deployment, I've seen keter+nginx work well together with the following `nginx` site configuration:
```
server {
   listen 80 default_server;
   server_name your.domain.tld;
   
   client_max_body_size 2M;

   location / {
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header Host $http_host;
       proxy_set_header X-NginX-Proxy true;

       proxy_pass http://127.0.0.1:3080/;
       proxy_redirect off;
       proxy_read_timeout 300;
   }
}
```
and the `keter.conf` as
```
root: /var/www/keter
listeners:
   - host: 127.0.0.1
     port: 3080
setuid: keter
env:
  KEY: value
  KEY2: value2
```

**Comment by chreekat** [comment]
Poor keter does feel a bit rough around the edges. It still feels a bit like an afterthought. (Are the initial author(s) using it much still? Does some Docker workflow replace it more thoroughly?)

Note you can read about its purpose here, at least: http://www.yesodweb.com/book/deploying-your-webapp

**Comment by BlakeRain** [comment]
I have been using Keter for quite a long time and I must admit that Keter has become, for me, a tool of some significance. I can confirm that it is being used in production environments without issue. Keter not only runs a number of our web services but also a fair number of background processes (workers, CH processes and such). I could bang on about how great this all is, but I'm sure you already know this.

I cannot say I find Keter to be an afterthought, although if memory serves I think that may have been the case. That being said, I cannot find fault with the decision to create Keter and my deployments would be more complicated without it.

I've not felt that Keter is particularly rough around the edges, and thinking about it there are only a few features I feel are missing:

+ **Control individual processes**

   Currently if I need to restart processes my options are: 1) to restart Keter itself, or 2) touch the Keter package in the `incoming` directory. Whilst it's quite rare that I need to do so, there have been a few times this has been necessary. I'm afraid to admit that I usually opt for the former approach which is, of course, less than ideal. Either way, this causes a restart of the entire application, rather than an individual process.

   There are also times when we have needed to stop _part_ of an application (say one of the workers) without bringing down the whole lot. This currently requires modification of the Keter configuration for the application and a redeployment. Whilst that is not a particularly onerous task for me I fear that, in my absence, my colleagues (to whom Haskell is an enigma) may come unstuck.

   I can imagine processes (in the stanza configuration format) being given names, and a series of commands such as:

   ```
   $ keter stop myapp:process
   $ keter start myapp:other-process
   ```

   Perhaps the state of processes within an application can be persisted across deployments and restarts in an SQLite database.

+ **Keter bundle file extension**

   This is probably a silly thing, but I wonder if we could accept `tar.gz` as a [viable extension](https://github.com/snoyberg/keter/blob/master/Keter/Main.hs#L152) for Keter bundles rather than just `.keter`? Whilst it is no difficulty to change the output extension of `tar` or simply rename the file, I've found that a number of archive managers don't recognize the `tar` in a `.keter` file correctly.

As you can no doubt tell from the lack of corresponding GitHub issues, I've not found any of these significantly irksome; perhaps because I encounter them so rarely.

In regards to Docker in the context of Keter, whilst I've had some success with it I find it so much easier to deploy Keter bundles to an already running server. I have no evidence left of this, unfortunately, but I do believe that the Docker image I did manage to deploy included Keter anyway. One advantage of not using Docker myself is that I can leave the responsibility of managing various servers and such to someone more skilled than I.

**Comment by 3noch** [comment]
@BlakeRain @chreekat @angerman Have any of you incorporated DB migrations with your keter deployments? I can't tell, but it seems like that would be tough.

**Comment by BlakeRain** [comment]
The strategy I tend to employ is to have a separate build target that performs the migration (via `persistent`) which I run against any databases during scheduled downtime. This makes the process quite straightforward:

1. `sudo stop keter` on all instances,
2. Tell the database platform to run a backup (I like to use [compose.io](https://compose.io)),
3. Run the migration tool, with optional manual intervention when advised by `persistent`,
4. Start Keter again on all instances.

That being said, for the more trivial applications where a built-in migration is acceptable (say if there is only a single deployment), I'm fairly happy to bundle it all into a single application.

**Comment by bermanjosh** [comment]
Within the yesod world, I've generally been able to do one-time "unsafe" migrations by deploying my app, once, with a default specified in the `models` file. I don't commit that change to my repo, so the next time I deploy, the unneeded default is overwritten. Granted, not the most elegant solution, but for how often the issue arises (not that often), it's worked fine.

**Comment by chreekat** [comment]
For the record, I use keter and think it's valuable! I just couldn't tell whether or not anyone else uses it, also. Glad to hear other peoples' experiences.

For me the rough edges are:

1. No PPA (yet) ( #70, #77)
2. yesod keter vs keter-pkg(?) vs the home-made script I had to write since neither of the former two did what I needed about 6 months ago.

@3noch our migrations are quite simple since we only have one running instance right now. If the migration succeeds, the app switches over. Otherwise, the transaction rolls back and the old instance stays up. We have some custom stuff to automate unsafe migrations, but I'm hoping to join forces with one of the other migration-management packages that are out on Hackage eventually.

**Comment by 3noch** [comment]
@chreekat I'd like to know/improve the story for migrations, so I started the discussion in #141.

**Comment by creichert** [comment]
I haven't had a chance to read through all the comments yet, but here are some thoughts:

- I have used keter extensively for nearly 2 year in production. For that reason, I keep an eye on all incoming bugs in case there is anything I can help with.

- In some of my recent projects, I use keter specifically for development, administrative and "backend" apps. One thing I've found is that iteration times with keter are significantly faster than other options (though, not as robust).

- I also use keter extensively for running hundreds background jobs on servers (using the `background` stanza). This makes is trivial to run smaller jobs (w/ or w/o a web-server).

I added some commentary about DB migrations in #141. tl;dr if at all possible, the best way I have found to do migrations is either:

- scheduled downtime
- maintain pre&post migration code paths and run the migrations on app startup. Keter does some work here to drain connections from the old app while bringing the new app up.

**Comment by creichert** [comment]
@chreekat FWIW, I use `postgresql-simple-migration` and it's great. I take a lot of care in production deployments to leave the db in a state where the old or new version of an app can still use the db schema in case something goes wrong. It incurs some development overhead, though (which is why i mention only in production).

**Comment by creichert** [comment]
Hopefully, everyone was able to get the answers they needed. Please reopen if there is anything left to discuss.
