### ISSUE TITLE
Question: Unsure how to manage 2 different domains with SSL certificates

### ISSUE THREAD

**Issue by Vlix** [snoyberg/keter#148]
I'm kind of a beginner with web dev, but I really like Yesod and Keter and would love to make this work:

I have two different domains pointing to the same VPS' IP address.
It says in the README.md that Keter can handle this and it shows 127.0.0.1 and 127.0.0.2 to differentiate between the two Yesod apps/domains it should handle, but I can't seem to figure out how I'd make that work?
Should the Yesod App's [config/settings.yml]'s [host: ] argument be set to [127.0.0.1] ?
Should I put an NGINX in front of Keter?
The NGINX option seems redundant, since I could just use that to handle the certificates.

It'd be great if the README.md would be a bit more specific as to what needs to happen with Yesod apps.

**Comment by tolysz** [comment]
I guess it is to me :)
Keter is fine in front.

       ssl:
        key: /opt/keter/etc/cert/hello.key
        certificate: /opt/keter/etc/cert/hello.crt
        chain-certificates:
          - /opt/keter/etc/middle.crt
          - /opt/keter/etc/root.crt

One of your sites can to have its cert configured in the main config the other needs to be configured via stanza ( https://github.com/snoyberg/keter/blob/914a999273b0b7fbbf10e3cab9da55f9874fa5f9/incoming/foo1_0/config/keter.yaml )

**Comment by Vlix** [comment]
Can they both be configured via stanza?
It'd make it a bit more consistent.

But thanks for the example at least!

**Comment by tolysz** [comment]
Yes, they can... If it will not work you'll need fairly recent versions
(including tls)
I can give my stack.yaml to build it... once I get home.
On 24 Jun 2016 17:01, "Felix Paulusma" <notifications@github.com> wrote:

Can they both be configured via stanza?
It'd make it a bit more consistent.

But thanks for the example at least!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/snoyberg/keter/issues/148#issuecomment-228385868>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAmDAsowPDBJPqva-OHTDreTStFAkNRYks5qO_9DgaJpZM4I94eK>
.

**Comment by Vlix** [comment]
Thanks, but I just downloaded this github folder and built it using stack. AND IT WORKS!

So thanks again, I'd been going at this for a day now, you helped me tons!

**Comment by tolysz** [comment]
@Vlix could you update the readme with (some) missing steps and close this ticket ;) Or just with a comment how to do it so others can reuse your method.

**Comment by Vlix** [comment]
I've sent a pull request where I added more information to the Multiple SSL certificates section.
Again, thanks for the help ;)
