### ISSUE TITLE
Keter failed to lauch bundle

### ISSUE THREAD

**Issue by ATDumbass** [snoyberg/keter#184]
Hi, I finally managed to get keter running, but I get the error "The hostname you have provided, kosutova.com, is not recognized." when I try to access the page. I looked into the `/opt/keter/log/keter/current.log` and found this error: `Error occured when launching bundle gallery: Codec.Compression.Zlib: premature end of compressed data stream` what is the problem here?

**Comment by creichert** [comment]
@ATDumbass Did you figure this out? I haven't seen this error in some time, but I think this may be two separate problems. Often, the Zlib compression error happens when you push a bundle for the first time but seems to be inconsequential. 

As  for the other error, can you post your keter config? How do you have `listeners` configured?

**Comment by ATDumbass** [comment]
In the end I did figure it out. The virtual machine was running out of memory during the build, so I made 1 GB swap file and it's fine now. Thanks for the reply though
