### ISSUE TITLE
keter-config.yaml is a directory?

### ISSUE THREAD

**Issue by davewripley** [snoyberg/keter#234]
I'm trying to get started on an Ubuntu 20.04 server by following the instructions in the README. I need to make a keter-config.yaml to put into /opt/keter/etc. But there's already a keter-config.yaml (which I did not create) in my /opt/keter/etc. Moreover, it's not a yaml file at all, but rather a directory, containing directories etc, incoming, log, and temp. Has something gone a bit haywire here?

**Comment by jappeace** [comment]
it doesn't matter where you put it, as long as you give the exact config path to keter, which is done in the systemd config:

```
ExecStart=/opt/keter/bin/keter /opt/keter/etc/keter-config.yaml
```

In your case it maybe a populated directory likely because you fed it a config.yaml with the root key pointing to the `/opt/keter/etc/keter-config.yaml` path.
It's safe to delete that directory because that root folder is only a working directory for keter.

**Comment by davewripley** [comment]
Okay; good to know it's safe to delete and replace with the correct file! I think if I made a mistake it was starting it up without any config at all, rather than having a config pointed to the wrong place. Thanks very much!
