### ISSUE TITLE
Installing Keter on digital ocean

### ISSUE THREAD

**Issue by RikJurriaans** [snoyberg/keter#81]
I don't know if this is an issue or not but when I try install keter via the setup-keter.sh file the scripts stops running when it comes to the cabal update command. It says that cabal update has been "Killed". I run an Ubuntu 14.04; 512 mb / 1 cpu; 20 gb ssd; 1 TB transfer; droplet.

**Comment by creichert** [comment]
It is most likely running out of memory, unfortunately. See here: https://github.com/snoyberg/keter/issues/76

If you want to provide a bit more debug output, I can look into it. A good option would be to show a sensible error message (from the script) and fail gracefully.

Otherwise, you can use `cabal-install` on your local machine and `scp` the resulting binary to `/opt/keter/bin` on your server.

**Comment by creichert** [comment]
> It says that cabal update has been "Killed". 

If you want, you can run `cabal update` and `cabal install keter` manually on the server. This might help us get a better idea of which command is failing. I still think it is a memory issue, though.

**Comment by RikJurriaans** [comment]
I just read, that probably the DO droplet is too weak for cabal. I'll fire a beefier server and try to compile  the keter binaries on that one. Thanks for the quick response I'll keep you posted. ;)

**Comment by MaxGabriel** [comment]
@RikJurriaans you don't need a larger server; just add swap space (See #76)

**Comment by RikJurriaans** [comment]
Works ;))) thanks people

**Comment by creichert** [comment]
No problem. Happy to help.

@MaxGabriel thanks
